#include "EEPROM.h"

#define ROLL_KP_ADDRESS  0
#define ROLL_KI_ADDRESS  4
#define ROLL_KD_ADDRESS  8 

#define PITCH_KP_ADDRESS  12
#define PITCH_KI_ADDRESS  16
#define PITCH_KD_ADDRESS  20

#define YAW_KP_ADDRESS  24
#define YAW_KI_ADDRESS  28
#define YAW_KD_ADDRESS  32

#define ROLL_ANGLE_KP_ADDRESS  36 
#define ROLL_ANGLE_KI_ADDRESS  40
#define ROLL_ANGLE_KD_ADDRESS  44

#define PITCH_ANGLE_KP_ADDRESS  48
#define PITCH_ANGLE_KI_ADDRESS  52
#define PITCH_ANGLE_KD_ADDRESS  56

//#define USE_STRORED_VALUES

extern float ROLL_KP,ROLL_KI,ROLL_KD,YAW_KP,YAW_KI,YAW_KD,PITCH_KP,PITCH_KI,PITCH_KD,ROLL_ANGLE_KP,ROLL_ANGLE_KI,ROLL_ANGLE_KD,PITCH_ANGLE_KP,PITCH_ANGLE_KI,PITCH_ANGLE_KD;

void initEEPROM(void)
{
  #ifdef USE_STORED_VALUES
  EEPROM.get(ROLL_KP_ADDRESS,ROLL_KP);
  EEPROM.get(ROLL_KI_ADDRESS,ROLL_KI);
  EEPROM.get(ROLL_KD_ADDRESS,ROLL_KD);
  
  EEPROM.get(PITCH_KP_ADDRESS,PITCH_KP);
  EEPROM.get(PITCH_KI_ADDRESS,PITCH_KI);
  EEPROM.get(PITCH_KD_ADDRESS,PITCH_KD);
  
  EEPROM.get(YAW_KP_ADDRESS,YAW_KP);
  EEPROM.get(YAW_KI_ADDRESS,YAW_KI);
  EEPROM.get(YAW_KD_ADDRESS,YAW_KD);
  
  EEPROM.get(PITCH_ANGLE_KP_ADDRESS,PITCH_ANGLE_KP);
  EEPROM.get(PITCH_ANGLE_KI_ADDRESS,PITCH_ANGLE_KI);
  EEPROM.get(PITCH_ANGLE_KD_ADDRESS,PITCH_ANGLE_KD);
  
  EEPROM.get(ROLL_ANGLE_KP_ADDRESS,ROLL_ANGLE_KP);
  EEPROM.get(ROLL_ANGLE_KI_ADDRESS,ROLL_ANGLE_KI);
  EEPROM.get(ROLL_ANGLE_KD_ADDRESS,ROLL_ANGLE_KD);
  #else
  EEPROM.put(ROLL_KP_ADDRESS,ROLL_KP);
  EEPROM.put(ROLL_KI_ADDRESS,ROLL_KI);
  EEPROM.put(ROLL_KD_ADDRESS,ROLL_KD);
  
  EEPROM.put(PITCH_KP_ADDRESS,PITCH_KP);
  EEPROM.put(PITCH_KI_ADDRESS,PITCH_KI);
  EEPROM.put(PITCH_KD_ADDRESS,PITCH_KD);
  
  EEPROM.put(YAW_KP_ADDRESS,YAW_KP);
  EEPROM.put(YAW_KI_ADDRESS,YAW_KI);
  EEPROM.put(YAW_KD_ADDRESS,YAW_KD);
  
  EEPROM.put(PITCH_ANGLE_KP_ADDRESS,PITCH_ANGLE_KP);
  EEPROM.put(PITCH_ANGLE_KI_ADDRESS,PITCH_ANGLE_KI);
  EEPROM.put(PITCH_ANGLE_KD_ADDRESS,PITCH_ANGLE_KD);
  
  EEPROM.put(ROLL_ANGLE_KP_ADDRESS,ROLL_ANGLE_KP);
  EEPROM.put(ROLL_ANGLE_KI_ADDRESS,ROLL_ANGLE_KI);
  EEPROM.put(ROLL_ANGLE_KD_ADDRESS,ROLL_ANGLE_KD);
  #endif
}

void writeEEPROM(uint16_t address,float value)
{
  EEPROM.put(address,value);
}
